[theme]


base="dark"
primaryColor="#4e0202"
backgroundColor="#161616"
secondaryBackgroundColor="#161616"



# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
